---
- name: Deploy Tomcat
  hosts: webservers
  become: yes
  tasks:
    - name: Install JDK11
      apt: name=openjdk-11-jre state=present

    - name: Install Tomcat9
      apt: name=tomcat9 state=present
    
    - name: Start web server
      service: name=tomcat9 state=started
    
    - name: Copy .war file
      copy: spring-petclinic.war dest=/usr/share/tomcat9-root/default_root/

    - name: Restart tomcat
      service: name=tomcat9 state=restart